version: "3"

services:
  price_server:
    restart: always
    container_name: price_service
    build: .
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: ${MONGO_URI}
    volumes:
      - ./.env:/etc/price-service/.env:ro
  worker_interval:
    restart: always
    container_name: worker_interval
    build:
      context: .
      dockerfile: ./Dockerfile.worker
    environment:
      MONGO_URI: ${MONGO_URI}
    volumes:
      - ./.env:/etc/price-service/.env:ro
  worker_lbank:
    restart: always
    container_name: worker_lbank
    command: /bin/worker lbank
    build:
      context: .
      dockerfile: ./Dockerfile.worker
    environment:
      MONGO_URI: ${MONGO_URI}
      LBANK_API_KEY: ${LBANK_API_KEY}
      LBANK_SECRET_KEY: ${LBANK_SECRET_KEY}
    volumes:
      - ./.env:/etc/price-service/.env:ro
  worker_supplies:
    restart: always
    container_name: worker_supplies
    command: /bin/worker supply
    build:
      context: .
      dockerfile: ./Dockerfile.worker
    environment:
      MONGO_URI: ${MONGO_URI}
      LBANK_API_KEY: ${LBANK_API_KEY}
      LBANK_SECRET_KEY: ${LBANK_SECRET_KEY}
    volumes:
      - ./.env:/etc/price-service/.env:ro
#  mongodb:
#    image: mongo:5.0
#    ports:
#      - 27017:27017
##    volumes:
##      - ~/apps/mongo:/data/db
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=root
#      - MONGO_INITDB_ROOT_PASSWORD=password
#      - MONGO_INITDB_DATABASE=coingecko
