version: "3"

services:
  price_server:
    restart: always
    container_name: price_service
    build: .
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: ${MONGO_URI}
    volumes:
      - ./.env:/etc/price-service/.env:ro
  worker_interval:
    restart: always
    container_name: worker_interval
    build:
      context: .
      dockerfile: ./Dockerfile.worker
    environment:
      MONGO_URI: ${MONGO_URI}
    volumes:
      - ./.env:/etc/price-service/.env:ro

