db.tokens.ensureIndex({id: 1})
db.tokens.ensureIndex({id: 1, symbol:1, name: 1})
db.tokens.ensureIndex({id: 1, name: 1})
db.tokens.ensureIndex({symbol:1, name: 1})
db.tokens.ensureIndex({symbol:1})
db.tokens.ensureIndex({name: 1})
db.tokens.ensureIndex({contracts: 1})
db.tokens.ensureIndex({"contracts.chain": 1})
db.tokens.ensureIndex({"contracts.contract_address": 1})
